# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 599)

        # # Code Added By Me.
        # This removes the window frame and sets a transparent background.
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(280, 40, 331, 511))
        self.frame_2.setStyleSheet("background-color: #FFFFF3;\n"
                                   "border-radius: 25px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.LoginLabel = QtWidgets.QLabel(self.frame_2)
        self.LoginLabel.setGeometry(QtCore.QRect(90, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setObjectName("LoginLabel")

        self.UsernameLabel = QtWidgets.QLabel(self.frame_2)
        self.UsernameLabel.setGeometry(QtCore.QRect(90, 120, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Light")
        font.setPointSize(10)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setObjectName("UsernameLabel")

        self.PasswordLabel = QtWidgets.QLabel(self.frame_2)
        self.PasswordLabel.setGeometry(QtCore.QRect(90, 250, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Light")
        font.setPointSize(10)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(90, 180, 191, 20))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(90, 300, 191, 20))
        self.label_7.setObjectName("label_7")

        self.UsernameEntry = QtWidgets.QLineEdit(self.frame_2)
        self.UsernameEntry.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.UsernameEntry.setText("")
        self.UsernameEntry.setObjectName("UsernameEntry")

        self.PasswordEntry = QtWidgets.QLineEdit(self.frame_2)
        self.PasswordEntry.setGeometry(QtCore.QRect(90, 290, 113, 20))
        self.PasswordEntry.setText("")
        self.PasswordEntry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordEntry.setObjectName("PasswordEntry")

        self.MakeAnAccountLabel = QtWidgets.QLabel(self.frame_2)
        self.MakeAnAccountLabel.setGeometry(QtCore.QRect(90, 340, 141, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.MakeAnAccountLabel.setFont(font)
        self.MakeAnAccountLabel.setObjectName("MakeAnAccountLabel")

        self.LoginButton = QtWidgets.QPushButton(self.frame_2)
        self.LoginButton.setGeometry(QtCore.QRect(100, 390, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("QPushButton {\n"
                                       "    border-radius: 12px;\n"
                                       "    background-color: #00D9C0;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: white;\n"
                                       "}")
        self.LoginButton.setObjectName("LoginButton")

        self.ExitButton = QtWidgets.QPushButton(self.frame_2)
        self.ExitButton.setGeometry(QtCore.QRect(264, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("QPushButton {\n"
                                      "    border-radius: 24px;\n"
                                      "    background-color: #FF4365;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    background-color:#FF6B85;\n"
                                      "}")
        self.ExitButton.setObjectName("ExitButton")
        self.ExitButton.clicked.connect(self.CloseApplication)

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 331, 561))
        self.frame.setStyleSheet("QFrame#frame {\n"
                                 "    border-radius: 25px;\n"
                                 "    background-color: #00D9C0;\n"
                                 "}\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.TitleLabel = QtWidgets.QLabel(self.frame)
        self.TitleLabel.setGeometry(QtCore.QRect(30, 10, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Light")
        font.setPointSize(28)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")

        self.DescriptionLabel = QtWidgets.QLabel(self.frame)
        self.DescriptionLabel.setGeometry(QtCore.QRect(40, 80, 261, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Light")
        font.setPointSize(16)
        self.DescriptionLabel.setFont(font)
        self.DescriptionLabel.setObjectName("DescriptionLabel")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PhotoOrganiser"))
        self.LoginLabel.setText(_translate("MainWindow", "Log In"))
        self.UsernameLabel.setText(_translate("MainWindow", "Username"))
        self.PasswordLabel.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "______________________________"))
        self.label_7.setText(_translate("MainWindow", "______________________________"))
        self.UsernameEntry.setPlaceholderText(_translate("MainWindow", "Enter Username"))
        self.PasswordEntry.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.MakeAnAccountLabel.setText(_translate("MainWindow", "Make an account"))
        self.LoginButton.setText(_translate("MainWindow", "Log In"))
        self.ExitButton.setText(_translate("MainWindow", "X"))
        self.TitleLabel.setText(_translate("MainWindow", "Photo Organiser"))
        self.DescriptionLabel.setText(_translate("MainWindow", "Placeholder Text"))

    def CloseApplication(self):
        QtWidgets.QApplication.instance().quit()


#### This stuff here makes the window draggable
# If im being 100% honest I have no clue how this works
# But it works and Im not spending a minute longer on this
class FramelessWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)

    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.old_pos = event.globalPos()

    def mouseMoveEvent(self, event):
        if hasattr(self, 'old_pos'):
            delta = QtCore.QPoint(event.globalPos() - self.old_pos)
            self.move(self.x() + delta.x(), self.y() + delta.y())
            self.old_pos = event.globalPos()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = FramelessWindow()
    window.show()
    sys.exit(app.exec_())
